# Generated by Django 2.1.1 on 2018-09-12 20:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temizlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120, verbose_name='Yazı Başlığı')),
                ('detay', ckeditor.fields.RichTextField(verbose_name='Detay')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('resim', models.ImageField(null=True, upload_to='', verbose_name='Temizlik Resmi')),
            ],
            options={
                'verbose_name_plural': 'Temizlik Hizmetleri',
            },
        ),
    ]
