# Generated by Django 2.1 on 2018-09-06 12:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daireno', models.CharField(max_length=120, verbose_name='Daire No')),
                ('kat', models.CharField(max_length=120, verbose_name='Bulunduğu Kat')),
                ('oda', models.CharField(max_length=120, verbose_name='Oda Sayısı')),
                ('alan', models.CharField(max_length=120, verbose_name='Dairenin Alanı')),
                ('blok', models.CharField(max_length=100, verbose_name='Blok Adı')),
                ('isinma', models.CharField(max_length=120, verbose_name='Isınma Tipi')),
                ('yon', models.CharField(max_length=120, verbose_name='Dairenin Yönü')),
                ('satis', models.BooleanField(verbose_name='Satış Durumu')),
                ('aciklama', ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name_plural': 'Dairelerimiz',
            },
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeadi', models.CharField(max_length=120, verbose_name='Proje Adı')),
                ('aciklama', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(null=True, upload_to='', verbose_name='Proje Resmi')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='Projefoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='', verbose_name='Proje Resmi')),
                ('proje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proje.Proje')),
            ],
            options={
                'verbose_name_plural': 'Proje Fotoğrafları',
            },
        ),
        migrations.AddField(
            model_name='daire',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proje.Proje'),
        ),
    ]
