# Generated by Django 2.1 on 2018-09-06 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proje',
            options={'ordering': ['-tarih'], 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AddField(
            model_name='proje',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Eklenme Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proje',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
    ]
