# Generated by Django 2.1 on 2018-09-06 12:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=120, verbose_name='Firma Adı')),
                ('sahibi', models.CharField(max_length=120, verbose_name='Firma Sahibi')),
                ('telefon', models.CharField(max_length=11, null=True, verbose_name='İş Telefonu')),
                ('telefon2', models.CharField(max_length=11, null=True, verbose_name='Cep Telefonu')),
                ('faks', models.CharField(max_length=11, null=True, verbose_name='Faks Numarası')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email Adresi')),
                ('adres', models.TextField(null=True, verbose_name='Adres')),
                ('hakkimizda', ckeditor.fields.RichTextField(null=True, verbose_name='Hakkımızda')),
                ('vizyon', ckeditor.fields.RichTextField(null=True, verbose_name='Vizyonumuz')),
                ('misyon', ckeditor.fields.RichTextField(null=True, verbose_name='Misyonumuz')),
                ('facebook', models.CharField(max_length=120, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=120, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(max_length=120, null=True, verbose_name='Youtube')),
                ('instagram', models.CharField(max_length=120, null=True, verbose_name='Instagram')),
                ('googlemapx', models.CharField(max_length=120, null=True, verbose_name='Google Map X Koordinatı')),
                ('googlemapy', models.CharField(max_length=120, null=True, verbose_name='Google Map Y Koordinatı')),
            ],
            options={
                'verbose_name_plural': 'Firmalar',
            },
        ),
    ]
