# Generated by Django 2.1 on 2018-09-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteriadi', models.CharField(max_length=120, verbose_name='Müşteri Adı')),
                ('kimlikno', models.CharField(max_length=11, null=True, verbose_name='T.C Kimlik No')),
                ('telefon', models.CharField(max_length=11, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail Adresi')),
                ('adres', models.TextField(null=True, verbose_name='Adres')),
                ('dogumtarihi', models.DateField(null=True, verbose_name='Doğum Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Musterigecmisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecmis', models.TextField(max_length=250, verbose_name='Müşteri Bilgisi')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.Musteri')),
            ],
            options={
                'verbose_name_plural': 'Müşteri Geçmişleri',
            },
        ),
    ]
