# Generated by Django 2.1.1 on 2018-09-18 18:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emlak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('Satılık', 1), ('Kiralık', 2)], default=1, max_length=1, verbose_name='Emlak Durumu')),
                ('tip', models.CharField(max_length=50, null=True, verbose_name='Emlak Tipi')),
                ('oda', models.CharField(max_length=50, null=True, verbose_name='Oda Sayısı')),
                ('kat', models.CharField(max_length=50, null=True, verbose_name='Bulunduğu Kat')),
                ('buyukluk', models.CharField(max_length=20, verbose_name='Büyüklük')),
                ('fiyat', models.CharField(max_length=50, verbose_name='Fiyatı')),
                ('resim', models.ImageField(upload_to='emlak/', verbose_name='Fotoğraf')),
                ('aciklama', ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama')),
                ('isinmatipi', models.TextField(null=True, verbose_name='Isınma Tipi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif İlan')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='İlan Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Emlak İlanları',
            },
        ),
    ]
