# Generated by Django 2.1.1 on 2018-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlak',
            name='durum',
            field=models.CharField(choices=[('1', 'Satılık'), ('2', 'Kiralık')], default=1, max_length=1, verbose_name='Emlak Durumu'),
        ),
    ]
