# Generated by Django 2.1.1 on 2018-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_auto_20180918_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emlak',
            name='isinmatipi',
            field=models.CharField(max_length=100, null=True, verbose_name='Isınma Tipi'),
        ),
    ]
