# Generated by Django 2.1.1 on 2018-09-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_auto_20180918_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='emlak',
            name='adres',
            field=models.TextField(null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='emlak',
            name='il',
            field=models.CharField(default=1, max_length=30, verbose_name='Bulunduğu İl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emlak',
            name='ilce',
            field=models.CharField(default=1, max_length=50, verbose_name='Bulunduğu İlçe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emlak',
            name='mahalle',
            field=models.CharField(default=1, max_length=50, verbose_name='Bulunduğu Mahalle'),
            preserve_default=False,
        ),
    ]
