# Generated by Django 2.1.1 on 2018-09-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0004_auto_20180918_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='emlak',
            name='ilanno',
            field=models.CharField(default=1, max_length=20, verbose_name='İlan No'),
            preserve_default=False,
        ),
    ]
