# Generated by Django 2.1.1 on 2018-09-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0005_emlak_ilanno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmlakFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='emlak/%Y/%m/%d', verbose_name='Resim')),
            ],
            options={
                'verbose_name_plural': 'Emlak Resimleri',
            },
        ),
        migrations.AlterField(
            model_name='emlak',
            name='resim',
            field=models.ImageField(upload_to='emlak/%Y/%m/%d', verbose_name='Fotoğraf'),
        ),
        migrations.AddField(
            model_name='emlakfoto',
            name='emlak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='emlak.Emlak'),
        ),
    ]
