# Generated by Django 2.1 on 2018-09-06 12:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120, verbose_name='Yazı Başlığı')),
                ('detay', ckeditor.fields.RichTextField(verbose_name='Detay')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('resim', models.ImageField(null=True, upload_to='', verbose_name='Haber Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Haber yayınlansın mı?')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Blogresim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resimb', models.ImageField(upload_to='', verbose_name='Resim Seç')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haber.Blog')),
            ],
            options={
                'verbose_name_plural': 'Haber Resimleri',
            },
        ),
    ]
