# Generated by Django 2.1 on 2018-09-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0002_auto_20180906_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogresim',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='haber.Blog'),
        ),
    ]
