# Generated by Django 2.1.1 on 2018-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Resim')),
            ],
            options={
                'verbose_name_plural': 'Resimler',
            },
        ),
    ]
